branches:
  only:
    - master
language: c
compiler: gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq valgrind
script:
  - make tests
  - tests/scripts/run.py
  - tests/scripts/valgrind.py
