branches:
  only:
    - master
language: c
compiler: gcc
install:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq valgrind
  - sudo apt-get install -y -qq --only-upgrade autoconf
script:
  - autoreconf -i
  - mkdir -p build
  - ./configure --prefix=$PWD/build --disable-shared
  - make
  - make install
  - make tests
  - tests/scripts/valgrind.py
  - tests/scripts/run.py
